version: '2'

services:
  dash_api:
    build: .
    container_name: "resale_api"
    env_file:
      - ./.env
    ports:
      - "8083:80"
    volumes:
      - ./code/src:/src
    depends_on:
      - db
    links:
      - db
  db:
    image: mongo
    container_name: mongodb